[package]
name = "tima"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "tima"
path = "src/main.rs"

[dependencies]
cranelift-codegen = "=0.136.1"
cranelift-frontend = "=0.136.1"
cranelift-module = "=0.136.1"
cranelift-native = "=0.136.1"
cranelift-object = "=0.136.1"
libloading = "=0.8.9"
object = { version = "=0.40.0", default-features = false, features = ["read", "write", "std", "coff", "elf", "macho", "pe"] }
png = "=0.18.1"
target-lexicon = "=0.13.5"
wasmi = { version = "=2.0.0", default-features = false, features = ["stable", "std", "validate"] }
webp-rust = "=0.3.1"
